// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUrYRg12q_uASiVFK3p4xbC9iKepafOOs',
    appId: '1:454956251433:web:9c4d4b82b9bb1cd190df38',
    messagingSenderId: '454956251433',
    projectId: 'chatapp-f81bb',
    authDomain: 'chatapp-f81bb.firebaseapp.com',
    storageBucket: 'chatapp-f81bb.appspot.com',
    measurementId: 'G-8R2GNKXWMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Vtz-DGRfmaogSmKXT_0WtkBjmFSbx8o',
    appId: '1:454956251433:android:226b59eabb668e1490df38',
    messagingSenderId: '454956251433',
    projectId: 'chatapp-f81bb',
    storageBucket: 'chatapp-f81bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxp4ZUfl6hkBeB1yV1dc6yl-3DChKcqzU',
    appId: '1:454956251433:ios:7705d074b5b915bd90df38',
    messagingSenderId: '454956251433',
    projectId: 'chatapp-f81bb',
    storageBucket: 'chatapp-f81bb.appspot.com',
    iosClientId: '454956251433-dolt7sbssen4kdjm9vccvfs0a4428iq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxp4ZUfl6hkBeB1yV1dc6yl-3DChKcqzU',
    appId: '1:454956251433:ios:7705d074b5b915bd90df38',
    messagingSenderId: '454956251433',
    projectId: 'chatapp-f81bb',
    storageBucket: 'chatapp-f81bb.appspot.com',
    iosClientId: '454956251433-dolt7sbssen4kdjm9vccvfs0a4428iq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
